CREATE TABLE IF NOT EXISTS `__PROJECT_ID__.__GOLD_DATASET__.categories` (
  category_id STRING NOT NULL,
  category_name STRING NOT NULL,
  parent_category STRING NOT NULL,
  category_kind STRING NOT NULL,
  description STRING,
  active BOOL NOT NULL,
  created_at TIMESTAMP NOT NULL
);

MERGE `__PROJECT_ID__.__GOLD_DATASET__.categories` AS target
USING UNNEST([
  STRUCT('coffee' AS category_id, 'Coffee' AS category_name, 'Food & Drink' AS parent_category, 'expense' AS category_kind, 'Coffee shops and coffee purchases' AS description),
  STRUCT('delivery', 'Delivery', 'Food & Drink', 'expense', 'Prepared-food delivery'),
  STRUCT('groceries', 'Groceries', 'Food & Drink', 'expense', 'Groceries and household food'),
  STRUCT('restaurants_bars', 'Restaurants & Bars', 'Food & Drink', 'expense', 'Restaurants, bars, and dining'),
  STRUCT('clothes_grooming', 'Clothes & Grooming', 'Home, Health & Clothes', 'expense', 'Clothing, grooming, and personal care'),
  STRUCT('fitness', 'Fitness', 'Home, Health & Clothes', 'expense', 'Gym, fitness, and exercise'),
  STRUCT('healthcare', 'Healthcare', 'Home, Health & Clothes', 'expense', 'Medical, dental, and healthcare'),
  STRUCT('home', 'Home', 'Home, Health & Clothes', 'expense', 'Household goods and everyday home spending'),
  STRUCT('pets', 'Pets', 'Home, Health & Clothes', 'expense', 'Pet care and supplies'),
  STRUCT('insurance', 'Insurance', 'Mortgage, Bills & School', 'expense', 'Insurance premiums and related costs'),
  STRUCT('housing', 'Housing', 'Mortgage, Bills & School', 'expense', 'Rent, mortgage, and core housing costs'),
  STRUCT('school', 'School', 'Mortgage, Bills & School', 'expense', 'School and tuition'),
  STRUCT('utilities', 'Utilities', 'Mortgage, Bills & School', 'expense', 'Utilities and recurring household bills'),
  STRUCT('babysitters', 'Babysitters', 'Recreation, Travel & Transit', 'expense', 'Babysitting and childcare'),
  STRUCT('books_media', 'Books & Media', 'Recreation, Travel & Transit', 'expense', 'Books and purchased media'),
  STRUCT('car', 'Car', 'Recreation, Travel & Transit', 'expense', 'Car ownership, maintenance, and fuel'),
  STRUCT('media', 'Media & Entertainment', 'Recreation, Travel & Transit', 'expense', 'Streaming, entertainment, and media'),
  STRUCT('recreation', 'Recreation', 'Recreation, Travel & Transit', 'expense', 'Recreation and leisure'),
  STRUCT('transportation', 'Transportation', 'Recreation, Travel & Transit', 'expense', 'Public transit, rides, parking, and local transportation'),
  STRUCT('travel_vacation', 'Travel & Vacation', 'Recreation, Travel & Transit', 'expense', 'Travel and vacations'),
  STRUCT('donations', 'Donations', 'Holiday & Giving', 'expense', 'Charitable donations'),
  STRUCT('gifts', 'Gifts', 'Holiday & Giving', 'expense', 'Gifts, birthdays, weddings, and celebrations'),
  STRUCT('kids_recreation', 'Kids Recreation', 'Holiday & Giving', 'expense', 'Kids recreation and activities'),
  STRUCT('holidays', 'Holidays', 'Holiday & Giving', 'expense', 'Holiday-specific spending'),
  STRUCT('home_repair', 'Home Repair', 'Home Repair', 'expense', 'Repairs, renovations, and home projects'),
  STRUCT('annual_subscriptions', 'Annual Subscriptions', 'Capital & Irregular', 'expense', 'Annual or irregular subscriptions'),
  STRUCT('major_purchase', 'Major Purchase', 'Capital & Irregular', 'expense', 'Large one-time purchases'),
  STRUCT('cash', 'Cash', 'Other', 'expense', 'Cash withdrawals and cash spending'),
  STRUCT('education', 'Education', 'Other', 'expense', 'Education outside regular school costs'),
  STRUCT('fees', 'Fees', 'Other', 'expense', 'Bank and service fees'),
  STRUCT('taxes', 'Taxes', 'Other', 'expense', 'Taxes and tax payments'),
  STRUCT('work_expenses', 'Work Expenses', 'Other', 'expense', 'Work-related expenses'),
  STRUCT('unclassified', 'Unclassified', 'Other', 'expense', 'Not yet classified'),
  STRUCT('paycheck', 'Paycheck', 'Income', 'income', 'Employment income'),
  STRUCT('interest_income', 'Interest Income', 'Income', 'income', 'Interest income'),
  STRUCT('other_income', 'Other Income', 'Income', 'income', 'Other income'),
  STRUCT('refund', 'Refund', 'Income', 'income', 'Refunds and reimbursements'),
  STRUCT('internal_transfer', 'Internal Transfer', 'Transfers', 'transfer', 'Transfers between owned accounts'),
  STRUCT('credit_card_payment', 'Credit Card Payment', 'Transfers', 'transfer', 'Credit-card payments'),
  STRUCT('loan_repayment', 'Loan Repayment', 'Transfers', 'transfer', 'Loan principal payments'),
  STRUCT('investment_activity', 'Investment Activity', 'Transfers', 'transfer', 'Investment purchases, sales, and sweeps')
]) AS seed
ON target.category_id = seed.category_id
WHEN MATCHED THEN UPDATE SET
  category_name = seed.category_name,
  parent_category = seed.parent_category,
  category_kind = seed.category_kind,
  description = seed.description,
  active = TRUE
WHEN NOT MATCHED THEN
  INSERT (category_id, category_name, parent_category, category_kind, description, active, created_at)
  VALUES (seed.category_id, seed.category_name, seed.parent_category, seed.category_kind, seed.description, TRUE, CURRENT_TIMESTAMP());

CREATE TABLE IF NOT EXISTS `__PROJECT_ID__.__GOLD_DATASET__.category_aliases` (
  source_system STRING NOT NULL,
  source_parent_category STRING,
  source_category STRING NOT NULL,
  category_id STRING NOT NULL,
  notes STRING,
  active BOOL NOT NULL,
  created_at TIMESTAMP NOT NULL
);

MERGE `__PROJECT_ID__.__GOLD_DATASET__.category_aliases` AS target
USING UNNEST([
  STRUCT('tiller' AS source_system, '' AS source_parent_category, 'Restaurants' AS source_category, 'restaurants_bars' AS category_id),
  STRUCT('tiller', '', 'Shopping', 'clothes_grooming'),
  STRUCT('tiller', '', 'Groceries', 'groceries'),
  STRUCT('tiller', '', 'Transfer', 'internal_transfer'),
  STRUCT('tiller', '', 'Transportation', 'transportation'),
  STRUCT('tiller', '', 'Entertainment', 'media'),
  STRUCT('tiller', '', 'Misc', 'unclassified'),
  STRUCT('tiller', '', 'Medical and Dental', 'healthcare'),
  STRUCT('tiller', '', 'Other Income', 'other_income'),
  STRUCT('tiller', '', 'Fitness', 'fitness'),
  STRUCT('tiller', '', 'Home Improvement', 'home_repair'),
  STRUCT('tiller', '', 'Utilities and Bills', 'utilities'),
  STRUCT('tiller', '', 'Travel', 'travel_vacation'),
  STRUCT('tiller', '', 'Paycheck', 'paycheck'),
  STRUCT('tiller', '', 'Bank Fees', 'fees'),
  STRUCT('tiller', '', 'Interest', 'interest_income'),
  STRUCT('tiller', '', 'Gifts', 'gifts'),
  STRUCT('tiller', '', 'Insurance', 'insurance'),
  STRUCT('tiller', '', 'Kids', 'kids_recreation'),
  STRUCT('tiller', '', 'Charity', 'donations'),
  STRUCT('tiller', '', 'Housing', 'housing'),
  STRUCT('tiller', '', 'Uncategorized', 'unclassified'),
  STRUCT('tiller', '', 'Education', 'education'),
  STRUCT('tiller', '', 'Taxes', 'taxes'),
  STRUCT('tiller', '', 'Subscriptions', 'annual_subscriptions'),
  STRUCT('tiller', '', 'Check', 'unclassified'),
  STRUCT('tiller', '', 'Pets', 'pets'),
  STRUCT('tiller', '', 'Loan Repayment', 'loan_repayment'),
  STRUCT('copilot', 'Food & Drink', 'Coffee', 'coffee'),
  STRUCT('copilot', 'Food & Drink', 'Delivery', 'delivery'),
  STRUCT('copilot', 'Food & Drink', 'Groceries', 'groceries'),
  STRUCT('copilot', 'Food & Drink', 'Restaurants & Bars', 'restaurants_bars'),
  STRUCT('copilot', 'Home, Health & Clothes', 'Clothes & Grooming', 'clothes_grooming'),
  STRUCT('copilot', '', 'Clothes', 'clothes_grooming'),
  STRUCT('copilot', 'Home, Health & Clothes', 'Gym', 'fitness'),
  STRUCT('copilot', 'Home, Health & Clothes', 'Healthcare', 'healthcare'),
  STRUCT('copilot', 'Home, Health & Clothes', 'Home', 'home'),
  STRUCT('copilot', 'Mortgage, Bills & School', 'Insurance', 'insurance'),
  STRUCT('copilot', 'Mortgage, Bills & School', 'Rent', 'housing'),
  STRUCT('copilot', 'Mortgage, Bills & School', 'School', 'school'),
  STRUCT('copilot', 'Mortgage, Bills & School', 'Utilities', 'utilities'),
  STRUCT('copilot', 'Recreation, Travel & Transit', 'Babysitters', 'babysitters'),
  STRUCT('copilot', 'Recreation, Travel & Transit', 'Books & Media', 'books_media'),
  STRUCT('copilot', 'Recreation, Travel & Transit', 'Car', 'car'),
  STRUCT('copilot', 'Recreation, Travel & Transit', 'Media', 'media'),
  STRUCT('copilot', 'Recreation, Travel & Transit', 'Recreation', 'recreation'),
  STRUCT('copilot', 'Recreation, Travel & Transit', 'Transportation', 'transportation'),
  STRUCT('copilot', 'Recreation, Travel & Transit', 'Travel & Vacation', 'travel_vacation'),
  STRUCT('copilot', 'Holiday / Presents', 'Donations', 'donations'),
  STRUCT('copilot', 'Holiday / Presents', 'Gifts', 'gifts'),
  STRUCT('copilot', 'Holiday / Presents', 'Kids rec', 'kids_recreation'),
  STRUCT('copilot', 'Holiday / Presents', 'Xmas', 'holidays'),
  STRUCT('copilot', 'Holiday / Presents', 'Christmas 2013', 'holidays'),
  STRUCT('copilot', 'Holiday / Presents', 'Ada’s Bday', 'gifts'),
  STRUCT('copilot', 'Holiday / Presents', 'Bruce’s Bday', 'gifts'),
  STRUCT('copilot', 'Holiday / Presents', 'brucie bike', 'gifts'),
  STRUCT('copilot', '', 'Crystal Xmas ‘25', 'holidays'),
  STRUCT('copilot', '', 'Other presents', 'gifts'),
  STRUCT('copilot', 'Other', 'Cash', 'cash'),
  STRUCT('copilot', 'Other', 'Education', 'education'),
  STRUCT('copilot', 'Other', 'Fee', 'fees'),
  STRUCT('copilot', 'Other', 'Taxes', 'taxes'),
  STRUCT('copilot', 'Other', 'Unclassified', 'unclassified'),
  STRUCT('copilot', 'Other', 'Work Expenses', 'work_expenses'),
  STRUCT('copilot', 'Other', 'New Baby Prep', 'major_purchase'),
  STRUCT('copilot', 'Capital: Other', 'Annual Subs', 'annual_subscriptions'),
  STRUCT('copilot', 'Capital: Other', 'Airpods', 'major_purchase'),
  STRUCT('copilot', 'Capital: Other', 'Car', 'major_purchase'),
  STRUCT('copilot', 'Capital: Other', 'Car Repair (wheels)', 'car'),
  STRUCT('copilot', 'Capital: Other', 'Clothing - annual', 'clothes_grooming'),
  STRUCT('copilot', 'Capital: Other', 'Deposit', 'internal_transfer'),
  STRUCT('copilot', 'Capital: Other', 'New iPhone', 'major_purchase'),
  STRUCT('copilot', 'Capital: Other', 'New rugs', 'major_purchase'),
  STRUCT('copilot', 'Capital: Other', 'Peleton', 'fitness'),
  STRUCT('copilot', 'Capital: Other', 'Rei', 'major_purchase'),
  STRUCT('copilot', 'Capital: Other', 'Taxes', 'taxes'),
  STRUCT('copilot', 'Home Repair', 'AC Fix ‘24', 'home_repair'),
  STRUCT('copilot', 'Home Repair', 'Basement Remodel', 'home_repair'),
  STRUCT('copilot', 'Home Repair', 'Bug spraying', 'home_repair'),
  STRUCT('copilot', 'Home Repair', 'Buy House', 'housing'),
  STRUCT('copilot', 'Home Repair', 'Electrical Update', 'home_repair'),
  STRUCT('copilot', 'Home Repair', 'Fix Bathroom Toiler', 'home_repair'),
  STRUCT('copilot', 'Home Repair', 'Fridge repair', 'home_repair'),
  STRUCT('copilot', 'Home Repair', 'Home repair', 'home_repair'),
  STRUCT('copilot', 'Home Repair', 'Home Repair: Furnace', 'home_repair'),
  STRUCT('copilot', 'Home Repair', 'Kitchen Redo', 'home_repair'),
  STRUCT('copilot', 'Home Repair', 'Leak', 'home_repair'),
  STRUCT('copilot', 'Home Repair', 'Replace Roof', 'home_repair'),
  STRUCT('copilot', 'Home Repair', 'Washer and Dryer', 'home_repair'),
  STRUCT('copilot', '', 'Fridge', 'major_purchase'),
  STRUCT('copilot', '', 'Garbage Disposal', 'major_purchase'),
  STRUCT('copilot', '', 'Litter robot', 'major_purchase'),
  STRUCT('copilot', '', 'Roof deck', 'home_repair'),
  STRUCT('copilot', 'Vacations', '10 Yr Staycation', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'Annas wedding', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'Crystal Trip', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'Deer Isle', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'Florida 24', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'France trip 24', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'France trip ‘25', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'Greece', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'Hannah PBurg - May', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'Maine ‘24', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'Maude’s Babyshower', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'Michigan 25', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'Offsite', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'Vacation: Hannah Florida', 'travel_vacation'),
  STRUCT('copilot', 'Vacations', 'Vacation: Matt’s wedding', 'travel_vacation'),
  STRUCT('copilot', '', 'Florida ‘25', 'travel_vacation'),
  STRUCT('copilot', '', 'Fitler Club', 'recreation'),
  STRUCT('copilot', '', 'Issues', 'unclassified'),
  STRUCT('copilot', '', 'Work Capital', 'work_expenses')
]) AS seed
ON target.source_system = seed.source_system
AND REGEXP_REPLACE(LOWER(COALESCE(target.source_parent_category, '')), r'[^a-z0-9]+', '') = REGEXP_REPLACE(LOWER(COALESCE(seed.source_parent_category, '')), r'[^a-z0-9]+', '')
AND REGEXP_REPLACE(LOWER(target.source_category), r'[^a-z0-9]+', '') = REGEXP_REPLACE(LOWER(seed.source_category), r'[^a-z0-9]+', '')
WHEN MATCHED THEN UPDATE SET
  category_id = seed.category_id,
  source_parent_category = seed.source_parent_category,
  source_category = seed.source_category,
  active = TRUE
WHEN NOT MATCHED THEN
  INSERT (source_system, source_parent_category, source_category, category_id, notes, active, created_at)
  VALUES (seed.source_system, NULLIF(seed.source_parent_category, ''), seed.source_category, seed.category_id, 'Seeded from Tiller/Copilot taxonomy review', TRUE, CURRENT_TIMESTAMP());
